"""Physical placement analyses over existing M3D slots."""

from .fast_region import (
    FastRegionCapacityError,
    FastRegionOccupancyPoint,
    FastRegionWorkloadComparison,
    PagePlacementResult,
    PageSlotAssignment,
    PhysicalSlotSelection,
    RandomPlacementSummary,
    compare_fast_region_placements,
    evaluate_fast_region_occupancy_sweep,
    place_pages_on_slots,
    select_physical_slots,
)
from .serving_e2e import (
    HierarchicalPlacementServingTimingResult,
    OccupancyServingClosurePoint,
    PlacementServingComparison,
    PlacementServingTimingResult,
    compare_placement_serving_performance,
    evaluate_placement_serving_timing,
    evaluate_metrics_placement_serving_timing,
    evaluate_hierarchical_placement_serving_timing,
    propagate_occupancy_sweep_to_serving,
)
from .moe_published_e2e import (
    MoEHierarchicalPlacementE2ECase,
    MoEPublishedPlacementE2ECase,
    PhysicalPlacementComparison,
    PhysicalPlacementPoint,
    TrafficClassLatency,
    evaluate_published_moe_placement_e2e,
    evaluate_published_moe_hierarchical_e2e,
)
from .nmp_feasibility import (
    GPUOnlyPlacementBaseline,
    NMPFeasibilityPoint,
    NMPPlacementPoint,
    NMPSweepSummary,
    NMPWorkloadClosure,
    evaluate_nmp_feasibility,
    sweep_nmp_feasibility,
)

__all__ = [
    "FastRegionCapacityError",
    "FastRegionOccupancyPoint",
    "FastRegionWorkloadComparison",
    "PagePlacementResult",
    "PageSlotAssignment",
    "PhysicalSlotSelection",
    "RandomPlacementSummary",
    "OccupancyServingClosurePoint",
    "PlacementServingComparison",
    "PlacementServingTimingResult",
    "HierarchicalPlacementServingTimingResult",
    "MoEPublishedPlacementE2ECase",
    "MoEHierarchicalPlacementE2ECase",
    "PhysicalPlacementComparison",
    "PhysicalPlacementPoint",
    "TrafficClassLatency",
    "GPUOnlyPlacementBaseline",
    "NMPFeasibilityPoint",
    "NMPPlacementPoint",
    "NMPSweepSummary",
    "NMPWorkloadClosure",
    "compare_fast_region_placements",
    "evaluate_fast_region_occupancy_sweep",
    "place_pages_on_slots",
    "select_physical_slots",
    "compare_placement_serving_performance",
    "evaluate_placement_serving_timing",
    "evaluate_metrics_placement_serving_timing",
    "evaluate_hierarchical_placement_serving_timing",
    "evaluate_published_moe_placement_e2e",
    "evaluate_published_moe_hierarchical_e2e",
    "evaluate_nmp_feasibility",
    "sweep_nmp_feasibility",
    "propagate_occupancy_sweep_to_serving",
]
